#!/usr/bin/env python3
"""Admit U09, bind U10 frame/audio, and dispatch U10 local render."""
from __future__ import annotations
import hashlib,json,os,tempfile
from datetime import datetime,timedelta,timezone
from pathlib import Path
R=Path(__file__).resolve().parents[1]
V=R/"working_assets/e40_production_20260814/u09_v3_local_authority_third_frost_wipe_exact_dialogue_v1/E40-U09-V3-LOCAL-AUTHORITY-EXACT-DIA008-THIRD-FROST-WIPE.mp4";M=R/"qa/e40_production_20260814/u09_v3_local_authority_third_frost_wipe_exact_dialogue_v1/E40_U09_V3_LOCAL_AUTHORITY_MACHINE_QA_V1.json";H=R/"qa/e40_production_20260814/u09_v3_local_authority_third_frost_wipe_exact_dialogue_v1/E40_U09_V3_ORIGINAL_RES_HUMAN_VISUAL_QA_V1.json";T=R/"qa/e40_production_20260814/u09_v3_local_authority_third_frost_wipe_exact_dialogue_v1/frame_0095_tail.png";AR=R/"qa/e40_preproduction_20260814/u09_parallel_kokoro_exact_audio_candidates_v1/E40_U09_PARALLEL_KOKORO_COMMERCIAL_RIGHTS_EVIDENCE_V1.json";A9=R/"workflow/releases/E40_U09_V3_RIGHTS_CLEARED_EXACT_DIALOGUE_UNIT_ADMISSION_20260814.json"
F10=R/"working_assets/e40_preproduction_20260814/u10_parallel_curtain_shadow_fan_lower_v1/E40_U10_PARALLEL_CANDIDATE_V3_EXACT_START_FRAME_720X1280.png";H10=R/"qa/e40_preproduction_20260814/u10_parallel_curtain_shadow_fan_lower_v1/E40_U10_PARALLEL_CANDIDATE_V3_ORIGINAL_RES_HUMAN_QA_V1.json";O10=R/"qa/e40_preproduction_20260814/u10_parallel_curtain_shadow_fan_lower_v1/E40_U10_PARALLEL_CANDIDATE_V3_OCR_AUDIT_V1.json";AU10=R/"working_assets/e40_production_20260814/u10_parallel_kokoro_exact_audio_candidates_v1/E40-DIA009_zf_001_speed1p4_normalized48k.wav";AQ10=R/"qa/e40_production_20260814/u10_parallel_kokoro_exact_audio_candidates_v1/E40_U10_PARALLEL_KOKORO_EXACT_AUDIO_MACHINE_QA_V1.json";AR10=R/"qa/e40_preproduction_20260814/u10_parallel_kokoro_exact_audio_candidates_v1/E40_U10_PARALLEL_KOKORO_COMMERCIAL_RIGHTS_EVIDENCE_V1.json";C10=R/"qa/e40_preproduction_20260814/u10_parallel_curtain_shadow_fan_lower_v1/E40_U09_TAIL_TO_U10_FRAME_CONTINUITY_QA_V1.json";A10=R/"workflow/releases/E40_U10_PARALLEL_EXACT_START_FRAME_ADMISSION_20260814.json"
S=R/"workflow/production_line/E40_TASK_LANES_V1.json";W=R/"workflow/work_queue.json";X=R/"workflow/CODEX_TO_CLAUDE.md";T9="E40-U09-V3-LOCAL-AUTHORITY-EXACT-DIALOGUE-FOUR-MARK-WIPE-PERFORMANCE-QA";T10="E40-U10-V3-LOCAL-AUTHORITY-YUNFEI-CURTAIN-REACTION-EXACT-DIA009-QA"
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return str(p.relative_to(R))
def st(x):return x.isoformat().replace("+00:00","Z")
def wr(p,x):
 p.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,ensure_ascii=False,indent=2)+"\n").encode();fd,t=tempfile.mkstemp(prefix=f".{p.name}.",dir=p.parent)
 try:
  with os.fdopen(fd,"wb") as f:f.write(b);f.flush();os.fsync(f.fileno())
  os.replace(t,p)
 except Exception:Path(t).unlink(missing_ok=True);raise
def main():
 if any(p.exists() for p in (A9,C10,A10)):raise SystemExit("FAIL_COLLISION")
 for p in (V,M,H,T,AR,F10,H10,O10,AU10,AQ10,AR10,S,W):
  if not p.is_file():raise SystemExit(f"FAIL_MISSING:{p}")
 m=json.loads(M.read_text());h=json.loads(H.read_text());ar=json.loads(AR.read_text());aq=json.loads(AQ10.read_text());ar10=json.loads(AR10.read_text())
 if not m.get("status","").startswith("PASS") or m.get("failures") or m.get("final_asr_similarity")!=1.0 or h.get("status")!="PASS_HUMAN_VISUAL_ADMISSION_READY" or ar.get("releaseBlocked") is not False:raise SystemExit("FAIL_U09_GATES")
 if not aq.get("status","").startswith("PASS") or ar10.get("releaseBlocked") is not False:raise SystemExit("FAIL_U10_AUDIO")
 n=datetime.now(timezone.utc);c={"canonical_script_sha256":"140d4b7b980bd8de58a874c56588a88256aa1c8883f50ce05c907a40a3355a9b","canonical_manifest_sha256":"773aff20a0036f619a14958585cdfd22738c2d2c7c49bb074bff173f208bd4f1"}
 wr(A9,{"schema":"qingshan.e40.u09.v3.unit_admission.v1","status":"PASS_U09_V3_ADMITTED_FOR_EPISODE_ASSEMBLY","admitted_at":st(n),"episode":"E40","unit":"U09",**c,"video_path":rel(V),"video_sha256":sha(V),"machine_qa":rel(M),"machine_qa_sha256":sha(M),"human_qa":rel(H),"human_qa_sha256":sha(H),"tail_frame":rel(T),"tail_frame_sha256":sha(T),"rights_evidence":rel(AR),"rights_evidence_sha256":sha(AR),"gates":{"exact_frame0":True,"exact_asr":True,"third_mark_wipe":True,"protected_marks_and_empty_fifth":True,"ocr_zero":True,"identity":True,"commercial_rights":True},"provider_posts":0,"credits":0,"release_status":"NOT_RELEASED_UNIT_ONLY"})
 wr(C10,{"schema":"qingshan.e40.u09_tail_to_u10_frame.continuity_qa.v1","status":"PASS_CONTINUITY_BINDING","reviewed_at":st(n),"predecessor_tail":rel(T),"predecessor_tail_sha256":sha(T),"candidate_frame":rel(F10),"candidate_frame_sha256":sha(F10),"checks":{"table_wipe_to_curtain_reaction_cut":"PASS_CANONICAL_REVERSE_ANGLE","warm_cool_hall_lighting":"PASS","yunfei_silhouette_and_fan":"PASS","fan_lowering_mid_action":"PASS","no_face_or_wardrobe_overclaim":"PASS","ocr_zero":"PASS"},"human_score":92,"failures":[]})
 wr(A10,{"schema":"qingshan.e40.u10.parallel.frame_audio_admission.v1","status":"PASS_U10_EXACT_START_FRAME_AUDIO_ADMITTED_FOR_LOCAL_VIDEO","admitted_at":st(n),"episode":"E40","unit":"U10",**c,"canonical_line":"……你倒看得清楚。","speaker":"云妃","frame_path":rel(F10),"frame_sha256":sha(F10),"human_qa":rel(H10),"human_qa_sha256":sha(H10),"ocr_qa":rel(O10),"ocr_qa_sha256":sha(O10),"continuity_qa":rel(C10),"continuity_qa_sha256":sha(C10),"selected_audio":rel(AU10),"selected_audio_sha256":sha(AU10),"audio_qa":rel(AQ10),"audio_qa_sha256":sha(AQ10),"rights_evidence":rel(AR10),"rights_evidence_sha256":sha(AR10),"provider_posts":0,"credits":0,"release_status":"NOT_RELEASED_FRAME_ONLY"})
 s=json.loads(S.read_text());cur=[x for x in s["tasks"] if x.get("task_id")==T9]
 if len(cur)!=1 or any(x.get("task_id")==T10 for x in s["tasks"]):raise SystemExit("FAIL_SCHEDULER")
 cur[0].update({"state":"TERMINAL","wait_scope":"NONE_TERMINAL","blocked_by":None,"progress":"U09_V3_FRAME0_ASR_WIPE_OCR_IDENTITY_RIGHTS_PASS_ADMITTED","last_progress_at":st(n),"next_action":"Terminal U09; U10 local render owns production.","next_due_at":None,"executor_next_wakeup_at":None,"evidence_ref":rel(A9),"evidence_sha256":sha(A9),"output_ref":rel(V),"output_sha256":sha(V),"completed_at":st(n),"terminal_status":"PASS_U09_V3_ADMITTED_FOR_EPISODE_ASSEMBLY"})
 s["tasks"].append({"task_id":T10,"lane_id":"U10_LOCAL_AUTHORITY_YUNFEI_CURTAIN_REACTION","state":"RUNNING","wait_scope":"NONE_ACTIVE_RUNNING","zero_cost":True,"deliverable_type":"U10_EXACT_FRAME_EXACT_DIA009_CURTAIN_SILHOUETTE_VIDEO_AND_QA","priority":181,"scope":["E40","U10","V3","LOCAL_AUTHORITY_ONLY","EXACT_FRAME0","EXACT_DIA009","YUNFEI_SILHOUETTE","FAN_LOWER","RIGHTS_CLEAR","NO_PROVIDER","NO_RELEASE"],"exact_predecessor_task_id":T9,"liveness_role":"PRODUCING","observation_only":False,"maximum_new_submissions":0,"authorization":False,"provider_post_allowed":False,"provider_query_allowed":False,"download_allowed":False,"provider_calls":0,"transactions":0,"credits":0,"blocked_by":None,"progress":"U10_FRAME_AUDIO_CONTINUITY_RIGHTS_BOUND_LOCAL_RENDER_RUNNING","last_progress_at":st(n),"next_action":"Render U10 local authority curtain silhouette/fan-lower reaction with exact DIA009; preserve hidden face and run frame0, ASR, OCR, visual, continuity, rights and duration QA.","lease_owner":"codex-e40-production:u10-v3-local","lease_expires_at":st(n+timedelta(hours=2)),"next_due_at":st(n+timedelta(minutes=10)),"execution_mode":"CONTINUOUS","executor_handle":"automation:e40","executor_task_id":T10,"executor_acknowledged_at":st(n),"executor_next_wakeup_at":st(n+timedelta(minutes=10)),"evidence_ref":rel(A10),"evidence_sha256":sha(A10),"audio_ref":rel(AU10),"audio_sha256":sha(AU10)});s["updated_at"]=st(n);wr(S,s)
 w=json.loads(W.read_text());w["latest_e40_u09_parallel_preproduction"].update({"status":"PASS_U09_V3_ADMITTED_FOR_EPISODE_ASSEMBLY","video":rel(V),"video_sha256":sha(V),"unit_admission":rel(A9),"unit_admission_sha256":sha(A9),"next_action":"Terminal U09; U10 local render running."});w["latest_e40_u10_parallel_preproduction"].update({"status":"PASS_U10_FRAME_AUDIO_ADMITTED_LOCAL_VIDEO_RUNNING","continuity_qa":rel(C10),"continuity_qa_sha256":sha(C10),"frame_admission":rel(A10),"frame_admission_sha256":sha(A10),"blocked_by":None,"active_task_id":T10,"next_action":s["tasks"][-1]["next_action"]});wr(W,w)
 with X.open("a",encoding="utf-8") as f:f.write(f"\n\n## E40 checkpoint {st(n)} — U09 admitted; U10 frame/audio bound and local render dispatched\n\n- U09 V3 `{rel(V)}` SHA=`{sha(V)}` passed frame0, DIA008 ASR=1.0, protected frost-wipe semantics, OCR0, HUMAN94, identity/rights; admission SHA=`{sha(A9)}`.\n- U09 tail to U10 curtain-reaction frame continuity passed SHA=`{sha(C10)}`. U10 binds Yunfei DIA009 audio SHA=`{sha(AU10)}`; frame/audio admission SHA=`{sha(A10)}`. Scheduler started `{T10}` with zero provider posts/credits. No release.\n");f.flush();os.fsync(f.fileno())
 print(json.dumps({"status":"PASS_U09_ADMITTED_U10_LOCAL_RENDER_RUNNING","u09_admission_sha256":sha(A9),"u10_admission_sha256":sha(A10)},ensure_ascii=False));return 0
if __name__=="__main__":raise SystemExit(main())
