#!/usr/bin/env python3
from __future__ import annotations
import argparse,copy,sys
from datetime import datetime,timedelta,timezone
from pathlib import Path
R=Path(__file__).resolve().parents[1];S=R/'workflow/production_line/E40_TASK_LANES_V1.json';sys.path.insert(0,'/Users/rogerwu/.local/share/backlotos/share/pipeline-tools')
from task_lane_state_store import commit_task_updates,read_scheduler_snapshot  # noqa:E402
P='E40-U18-V34-PER-BUNDLE-ROOT-PERSISTENCE-AUTHORITY-TASK-LOCAL-REMOTE-WAIT';T='E40-U18-V35-ONE-TIME-ROOT-PERSISTENCE-AUTHORITY-SCHEMA-QA';N='E40-U18-V36-REAL-ONE-TIME-ROOT-PERSISTENCE-AUTHORITY-TASK-LOCAL-REMOTE-WAIT'
def z(x):return x.astimezone(timezone.utc).isoformat().replace('+00:00','Z')
def main():
 a=argparse.ArgumentParser();a.add_argument('action',choices=['register','terminal-and-wait']);a.add_argument('--evidence-ref',required=True);a.add_argument('--evidence-sha256',required=True);o=a.parse_args();n=datetime.now(timezone.utc);s=read_scheduler_snapshot(S);b={x['task_id']:copy.deepcopy(x) for x in s.payload['tasks']}
 if o.action=='register':
  p=b[P];p.update({'state':'TERMINAL','wait_scope':'NONE_TERMINAL','next_due_at':None,'completed_at':z(n),'terminal_status':'HANDOFF_TO_V35_ONE_TIME_AUTHORITY_SCHEMA_QA'});[p.pop(k,None) for k in ['execution_mode','executor_handle','executor_task_id','executor_acknowledged_at','executor_next_wakeup_at']]
  t={'task_id':T,'lane_id':'U18_ISOLATED_ASSET_ACQUISITION','state':'QA','zero_cost':True,'deliverable_type':'ONE_TIME_ROOT_PERSISTENCE_AUTHORITY_SCHEMA_QA','priority':205,'scope':['E40','U18','V35','LOCAL_ONLY','NO_REAL_AUTHORITY','NO_EXECUTION','NO_NETWORK'],'exact_predecessor_task_id':P,'liveness_role':'PRODUCING','observation_only':False,'maximum_new_submissions':0,'authorization':False,'provider_post_allowed':False,'provider_query_allowed':False,'download_allowed':False,'provider_calls':0,'transactions':0,'credits':0,'wait_scope':'NONE_ACTIVE_QA','progress':'REGISTERED_V35_ONE_TIME_AUTHORITY_SCHEMA_QA','last_progress_at':z(n),'next_action':'Compile/test one-time root persistence authority document schema only.','lease_owner':'codex-e40-next-unit-audit:u18-v35','lease_expires_at':z(n+timedelta(hours=2)),'next_due_at':z(n+timedelta(minutes=20)),'execution_mode':'CONTINUOUS','executor_handle':'agent:/root/e40_next_unit_audit','executor_task_id':T,'executor_acknowledged_at':z(n),'executor_next_wakeup_at':z(n+timedelta(minutes=10)),'evidence_ref':o.evidence_ref,'evidence_sha256':o.evidence_sha256};u={P:p,T:t}
 else:
  t=b[T];t.update({'state':'TERMINAL','wait_scope':'NONE_TERMINAL','next_due_at':None,'completed_at':z(n),'terminal_status':'PASS_V35_ONE_TIME_AUTHORITY_SCHEMA_NO_EXECUTION','progress':'PASS_V35_GENERIC_EXPIRED_MISMATCH_REPLAY_ACTION_AND_VALID_TESTS','evidence_ref':o.evidence_ref,'evidence_sha256':o.evidence_sha256});[t.pop(k,None) for k in ['execution_mode','executor_handle','executor_task_id','executor_acknowledged_at','executor_next_wakeup_at']]
  q={'task_id':N,'lane_id':'U18_ISOLATED_ASSET_ACQUISITION','state':'REMOTE_WAIT','zero_cost':True,'deliverable_type':'REAL_ONE_TIME_ROOT_PERSISTENCE_AUTHORITY_TASK_LOCAL_REMOTE_WAIT','priority':206,'scope':['E40','U18','V36','TASK_LOCAL','OFFLINE_ONLY','NO_WATCH','NO_NETWORK'],'exact_predecessor_task_id':T,'liveness_role':'PRODUCING','observation_only':False,'maximum_new_submissions':0,'authorization':False,'provider_post_allowed':False,'provider_query_allowed':False,'download_allowed':False,'provider_calls':0,'transactions':0,'credits':0,'wait_scope':'TASK_LOCAL','blocked_by':'REAL_FRESH_EXACT_V31_BUNDLE_BOUND_ONE_TIME_ROOT_PERSISTENCE_AUTHORIZATION_NOT_PRESENT','progress':'V35_SCHEMA_READY_WAITING_REAL_ONE_TIME_ROOT_PERSISTENCE_AUTHORIZATION','last_progress_at':z(n),'next_action':'Wake only on a real fresh one-time root persistence authorization conforming to V35 and bound to one exact V31 bundle; no fixture authority and no actions.','lease_owner':'codex-e40-next-unit-audit:u18-v36','lease_expires_at':z(n+timedelta(hours=24)),'next_due_at':z(n+timedelta(hours=12)),'execution_mode':'CONTINUOUS','executor_handle':'agent:/root/e40_next_unit_audit','executor_task_id':N,'executor_acknowledged_at':z(n),'executor_next_wakeup_at':z(n+timedelta(hours=6)),'evidence_ref':o.evidence_ref,'evidence_sha256':o.evidence_sha256};u={T:t,N:q}
 print(commit_task_updates(S,base_snapshot=s,task_updates=u,writer_id='codex-e40-next-unit-audit:u18-v35'))
if __name__=='__main__':main()
