#!/usr/bin/env python3
"""Synchronise verified E59 assets into its dedicated reuse library.

This is a migration/repair tool, not an admission tool.  It only copies
existing PASS/LOCKED decisions with SHA-verified artifacts.  It never creates
media and deliberately leaves assets without evidence absent, so S3 can plan
only the genuinely missing work.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


RUNTIME = Path("/Users/rogerwu/nalu_runtime_e59")
LIBRARY = RUNTIME / "runtime/asset_library.json"
REGISTRY = RUNTIME / "runtime/nalu_character_asset_registry.json"
Q1_INDEX = (
    RUNTIME
    / "workflow/nalu/E59/preproduction/reports/qa/q1/E59_KEYFRAME_Q1_INDEX.json"
)
REPORT = RUNTIME / "runtime/reports/E59_LOCKED_ASSET_LIBRARY_SYNC.json"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verified_artifact(path_text: str, expected_sha: str, role: str) -> dict:
    path = Path(path_text)
    if not path.is_file():
        raise SystemExit(f"missing artifact: {path}")
    actual = sha256(path)
    if actual != expected_sha:
        raise SystemExit(f"sha mismatch: {path}: {actual} != {expected_sha}")
    forbidden = ("YEWUJIANG", "/Users/rogerwu/nalu_runtime/")
    if any(token in str(path) for token in forbidden):
        raise SystemExit(f"forbidden cross-line path: {path}")
    return {"path": str(path), "sha256": actual, "role": role}


def locked_row(asset_id: str, label: str, artifacts: list[dict], authority: dict) -> dict:
    return {
        "asset_id": asset_id,
        "label": label,
        "status": "LOCKED",
        "qa": {
            "status": "PASS",
            "authority": authority,
        },
        "artifacts": artifacts,
        "migration_note": (
            "Existing verified E59 evidence registered for paid-reuse detection; "
            "no media was generated by this sync."
        ),
    }


def main() -> int:
    library = read_json(LIBRARY)
    registry = read_json(REGISTRY)
    q1 = read_json(Q1_INDEX)
    if q1.get("status") != "ALL_ADMITTED":
        raise SystemExit("Q1 index is not ALL_ADMITTED")

    assets = library.setdefault("assets", {})
    characters = assets.setdefault("characters", {})
    props = assets.setdefault("props", {})
    scenes = assets.setdefault("scenes", {})
    synced: list[str] = []

    for character_id, row in (registry.get("characters") or {}).items():
        if row.get("status") != "LOCKED" or row.get("qa_status") != "PASS":
            continue
        path_to_sha = row.get("canonical_reference_sha256") or {}
        artifacts = [
            verified_artifact(path, expected, "CANONICAL_IDENTITY_VIEW")
            for path, expected in path_to_sha.items()
        ]
        authority = {
            "kind": "CHARACTER_REGISTRY_LOCK",
            "registry": str(REGISTRY),
            "review_file": row.get("qa_review_file"),
            "review_file_sha256": row.get("qa_review_file_sha256"),
        }
        characters[character_id] = locked_row(
            character_id,
            row.get("display_name") or row.get("canonical_name") or character_id,
            artifacts,
            authority,
        )
        synced.append(character_id)

        view_paths = list(row.get("canonical_reference_paths") or [])
        for view_name, marker in (
            ("FRONT_NEUTRAL_HEADSHOT", "__FRONT_NEUTRAL_HEADSHOT_"),
            ("THREE_QUARTER_BUST", "__THREE_QUARTER_BUST_"),
        ):
            matches = [path for path in view_paths if marker in Path(path).name]
            if len(matches) != 1:
                raise SystemExit(
                    f"{character_id}: expected one {view_name} path, found {matches}"
                )
            path = matches[0]
            view_id = f"{character_id}__{view_name}"
            characters[view_id] = locked_row(
                view_id,
                f"{row.get('display_name') or character_id} {view_name}",
                [verified_artifact(path, path_to_sha[path], view_name)],
                authority,
            )
            synced.append(view_id)

    # The v4 contract uses the canonical returning-role id while the migrated
    # legacy registry retained its old subject key.  This is an id alias, not
    # a creative identity substitution: the locked row itself names the same
    # role as "侍女／迎客姑娘" and carries three admitted canonical views.
    aliases = {"CHAR-E57-GREETER": "maid_group"}
    for canonical_id, legacy_id in aliases.items():
        source = (registry.get("characters") or {}).get(legacy_id)
        if not source or source.get("status") != "LOCKED" or source.get("qa_status") != "PASS":
            raise SystemExit(f"locked alias source missing: {canonical_id} <- {legacy_id}")
        path_to_sha = source.get("canonical_reference_sha256") or {}
        all_artifacts = [
            verified_artifact(path, expected, "CANONICAL_IDENTITY_VIEW")
            for path, expected in path_to_sha.items()
        ]
        authority = {
            "kind": "CHARACTER_REGISTRY_ID_ALIAS",
            "canonical_id": canonical_id,
            "legacy_registry_id": legacy_id,
            "registry": str(REGISTRY),
            "review_file": source.get("qa_review_file"),
            "review_file_sha256": source.get("qa_review_file_sha256"),
        }
        characters[canonical_id] = locked_row(
            canonical_id, "迎客姑娘", all_artifacts, authority
        )
        synced.append(canonical_id)
        for view_name, marker in (
            ("FRONT_NEUTRAL_HEADSHOT", "__FRONT_NEUTRAL_HEADSHOT_"),
            ("THREE_QUARTER_BUST", "__THREE_QUARTER_BUST_"),
        ):
            matches = [path for path in path_to_sha if marker in Path(path).name]
            if len(matches) != 1:
                raise SystemExit(f"{legacy_id}: expected one {view_name} path")
            path = matches[0]
            view_id = f"{canonical_id}__{view_name}"
            characters[view_id] = locked_row(
                view_id,
                f"迎客姑娘 {view_name}",
                [verified_artifact(path, path_to_sha[path], view_name)],
                authority,
            )
            synced.append(view_id)

    fixed = {
        "SET-VEIL-CURTAINS": (
            "三层纱幕帷幕",
            RUNTIME / "workflow/nalu/E59/identity/plates/E59_gauze_curtain_6268558b-6b43-4f8f-88b7-0fe2f8fb9242.png",
            "props",
        ),
        "PROP-BAMBOO-CHAIR": (
            "竹椅",
            RUNTIME / "workflow/nalu/E59/identity/props_r2_source/PROP-BAMBOO-CHAIR.png",
            "props",
        ),
        "PROP-BIG-BOWL": (
            "大碗", RUNTIME / "runtime/character_sources/large_bowl.png", "props"
        ),
        "PROP-BRUSH-INK": (
            "笔墨",
            RUNTIME / "workflow/nalu/E59/identity/props_r2_source/PROP-BRUSH-INK.png",
            "props",
        ),
        "PROP-XUAN-PAPER": (
            "誊诗宣纸",
            RUNTIME / "runtime/character_sources/copied_poem_paper.png",
            "props",
        ),
    }
    for asset_id, (label, path, category) in fixed.items():
        artifact = verified_artifact(str(path), sha256(path), "LOCKED_REFERENCE_CARD")
        target = props if category == "props" else scenes
        target[asset_id] = locked_row(
            asset_id,
            label,
            [artifact],
            {"kind": "EXISTING_E59_LOCKED_ASSET", "source": str(path)},
        )
        synced.append(asset_id)

    # The fan has no isolated legacy card, but its first-use keyframe was
    # explicitly reviewed and admitted by Q1.  Register that evidence as an
    # in-scene reference; do not invent a standalone card.
    fan_result = next(
        (row for row in q1.get("results", []) if row.get("item_id") == "E59-S06-01"),
        None,
    )
    if not fan_result or fan_result.get("status") != "ADMITTED":
        raise SystemExit("admitted S06-01 fan evidence is missing")
    fan_path = Path(fan_result["asset_path"])
    fan_artifact = verified_artifact(
        str(fan_path), fan_result["asset_sha256"], "IN_SCENE_LOCKED_REFERENCE"
    )
    props["PROP-FOLDING-FAN"] = locked_row(
        "PROP-FOLDING-FAN",
        "折扇",
        [fan_artifact],
        {
            "kind": "KEYFRAME_Q1_ADMISSION",
            "q1_index": str(Q1_INDEX),
            "unit_id": fan_result.get("unit_id"),
            "item_id": fan_result.get("item_id"),
        },
    )
    synced.append("PROP-FOLDING-FAN")

    library["updated_at"] = datetime.now(timezone.utc).isoformat()
    library["updated_by"] = Path(__file__).name
    LIBRARY.write_text(json.dumps(library, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    report = {
        "schema": "nalu.e59.locked_asset_library_sync.v1",
        "status": "PASS",
        "library": str(LIBRARY),
        "library_sha256": sha256(LIBRARY),
        "character_registry": str(REGISTRY),
        "q1_index": str(Q1_INDEX),
        "synced_count": len(synced),
        "synced_ids": sorted(synced),
        "intentionally_missing_ids": ["SET-SUMMIT-BOULDER"],
        "paid_posts": 0,
        "forbidden_path_scan": "PASS",
    }
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
